version: '2.4'

services:      
  web:
    build: ./app
    container_name: web
    restart: always
    volumes:
      - ./app/:/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - database
      
  database:
    image: postgres:13.0
    restart: always
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - 5432:5432
      
  nginx:
      build: ./nginx
      restart: always
      container_name: nginx
      ports:
        - 7777:80
      depends_on:
        - web
        
  grafana:
    image: grafana/grafana
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://grafana:3000
      GF_SECURITY_ADMIN_PASSWORD: PINLOX!@#
    
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    expose:
      - 8123
      - 9000
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.xml

volumes:
  postgres_data:

